version: '3.8'

services:

  adminer:
    container_name: airvault_adminer
    image: adminer
    ports:
      - "8081:8080"

  db:
    container_name: airvault_db
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=airvault
    ports:
      - "5432:5432"

  api:
    container_name: airvault_api
    build: ./api
    depends_on:
      - db
    environment:
      - DB_URL=postgres://admin:admin@db:5432/airvault
      - JWT_SECRET=Change_me
      - ITEMS_CYPHER_KEY=Secret_Passphrase
    ports:
      - "3000:3000"
    command: sh -c "npm run db:migrate ; npm start"

  webapp:
    container_name: airvault_webapp
    build: ./webapp
    depends_on:
      - api
    ports:
      - "8080:80"

