version: '3.8'

services:

  db:
    container_name: airvault_db
    image: postgres:13.1-alpine
    env_file:
      - db.env
    ports:
      - 5432:5432

  db_test:
    container_name: airvault_db_test
    image: postgres:13.1-alpine
    env_file:
      - db_test.env
    ports:
      - 5433:5432

  adminer:
    container_name: airvault_adminer
    image: adminer
    ports:
      - 8081:8080
